### PR TITLE
Use sysctl to identify device model

### PR DESCRIPTION
**Pull request by seanchristians**
Hi there, the sysctl tool provides a much simpler and more reliable way of retrieving the device model.

### CODE REVIEW

**Comment by arubdesu** [comment]
Hmm, model is not functionally used in the script, it just echo's to the log? Do we need it at all?

**Comment by grahampugh** [comment]
@seanchristians thanks for your contribution. `sysctl -b hw.model` does not work here as that is a binary output. However, `sysctl -n hw.model` does work (this is a string output), and is one line less of code than our current method. If you make that correction and add the full path to /usr/sbin/sysctl we can accept the PR.

@arubdesu `$model` is used in some of the EAs but not the XProtect EA. It was included for a consistent output but could be removed from the XProtect one.

**Comment by seanchristians** [comment]
Thanks for the feedback. Changes made.

**Review by headmin — APPROVED** [review]
LGTM. 

Thanks for the contribution.

**Pull request merged**
